export { ForumSceleton } from './forum-sceleton'
export { CommunitySceleton } from './community-sceleton'
export { ProfileInfoSceleton } from './item/profile-info'
export { DepartmentSceleton } from './department-sceleton'
export { ShopSceleton } from './shop-sceleton'
export { PostContentSceleton } from './post-content'