export { ForumSceleton } from './forum'
export { CommentSceleton } from './comment'
export { PostSceleton } from './post'
export { UserSceleton } from './user'
export { ProfileInfoSceleton } from './item/profile-info'